baseurl = "https://serene-bartik-4a0b34.netlify.com"
languageCode = "en-us"
title = "An Experimental, Self-Managed, Shared Work Space"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Bruce Eckel"
	description = "An Experimental, Self-Managed, Shared Work Space"

	logo = "/images/circle.png"
	favicon = "images/favicon.png"
	banner_image = "/images/banner.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "#18ADFB"
    	accent  = "#18ADFB"
    	header_color = "#18ADFB"
    	footer_color = "#18ADFB"
    	h1_ruler_color= "#18ADFB"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	#twitter = ""
	#github  = "AtomicKotlin/AtomicKotlin-hugo"
	email   = "mindviewinc@gmail.com"

[[menu.main]]
  name   = "Evolve"
  url    = "evolve/"
  weight = 10

# [[menu.main]]
#   name   = "Book Sample"
#   url    = "sample/"
#   weight = 20
#
# [[menu.main]]
#   name   = "Early Access"
#   url    = "earlyaccess/"
#   weight = 30
#
# [[menu.main]]
#   name   = "Print Book"
#   url    = "printbook/"
#   weight = 40
#
# [[menu.main]]
# 	name   = "Exercises"
# 	url    = "exercises/"
# 	weight = 70

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 200


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
